#!/bin/sh

module purge
module load OpenFOAM/10-foss-2022a
source $FOAM_BASH

cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

