#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

U=$1
R=$2
Y=$3

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

python3 cylinder_gmsh_generator.py -U $U -R $R -Y $Y
gmsh -3 -format msh2 -o gmsh.msh gmsh.geo > log.gmsh

rm -rf constant/polyMesh
runApplication gmshToFoam gmsh.msh
python3 correct_boundary.py > temp.$$
mv temp.$$ constant/polyMesh/boundary
