#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

module purge
module load OpenFOAM/10-foss-2022a
source $FOAM_BASH

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
rm -rf 0/p 0/U 0/phi

