#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

U=$1
R=$2
Y=$3

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

echo
python3 cylinder_block_mesh_generator.py -U $U -R $R -Y $Y
runApplication blockMesh
