#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

echo
python3 cylinder_block_mesh_generator.py
runApplication blockMesh
checkMesh
